// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeSMCf20cd2mMZaY1IzslbF_8Qxfe-1Vc',
    appId: '1:806122804919:web:fd84b8e26b2a7f87e25f32',
    messagingSenderId: '806122804919',
    projectId: 'nickf2k-blog',
    authDomain: 'nickf2k-blog.firebaseapp.com',
    storageBucket: 'nickf2k-blog.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkUcItKFe01UJmjJAd2QIXUHPea9LvLfo',
    appId: '1:806122804919:android:c4df95e8c4309389e25f32',
    messagingSenderId: '806122804919',
    projectId: 'nickf2k-blog',
    storageBucket: 'nickf2k-blog.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV4hYuahPiocrA8IztyR7yk_9qLFX8xP0',
    appId: '1:806122804919:ios:2c9c2c2efd3c76c0e25f32',
    messagingSenderId: '806122804919',
    projectId: 'nickf2k-blog',
    storageBucket: 'nickf2k-blog.appspot.com',
    iosClientId: '806122804919-80kpfbb68ql6bo8g821i3jedusq48u1q.apps.googleusercontent.com',
    iosBundleId: 'com.example.nickf2kBlog',
  );
}
